import type { FenceMonth, Service, Slide } from "@/lib/api/types";

const monthNames = [
  "Январь",
  "Февраль",
  "Март",
  "Апрель",
  "Май",
  "Июнь",
  "Июль",
  "Август",
  "Сентябрь",
  "Октябрь",
  "Ноябрь",
  "Декабрь",
] as const;

const buildFenceMonths = (serviceId: string, approvedUntilMonthId: number): FenceMonth[] =>
  monthNames.map((name, index) => ({
    id: `fence-${serviceId}-${index + 1}`,
    name,
    isApproved: index + 1 <= approvedUntilMonthId,
  }));

type SlideSeed = Omit<Slide, "order" | "children"> & {
  order?: number;
  children?: SlideSeed[];
};

const compareSlides = (left: SlideSeed, right: SlideSeed) => {
  const leftOrder = left.order ?? Number.MAX_SAFE_INTEGER;
  const rightOrder = right.order ?? Number.MAX_SAFE_INTEGER;
  if (leftOrder === rightOrder) {
    return left.name.localeCompare(right.name, "ru");
  }
  return leftOrder - rightOrder;
};

const normalizeSlidesOrder = (items: SlideSeed[]): Slide[] =>
  [...items]
    .sort(compareSlides)
    .map((slide, index) => ({
      ...slide,
      order: index + 1,
      children: slide.children?.length ? normalizeSlidesOrder(slide.children) : undefined,
    }));

export const servicesMock: Service[] = [
  { id: "analytics", name: "Analytics Platform" },
  { id: "billing", name: "Billing Service" },
  { id: "support", name: "Support Portal" },
];

const slidesSeed: Record<string, SlideSeed[]> = {
  analytics: [
    {
      id: "a-1",
      serviceId: "analytics",
      name: "Overview",
      description: "Main performance dashboard",
      status: "published",
      isVisible: true,
      isFeatured: true,
    },
    {
      id: "a-2",
      serviceId: "analytics",
      name: "Funnels",
      description: "Step conversion analysis",
      status: "review",
      isVisible: true,
      isFeatured: false,
      children: [
        {
          id: "a-2-1",
          serviceId: "analytics",
          name: "Checkout Funnel",
          description: "Cart to purchase steps",
          status: "published",
          isVisible: true,
          isFeatured: true,
        },
        {
          id: "a-2-2",
          serviceId: "analytics",
          name: "Signup Funnel",
          description: "Landing to account creation",
          status: "review",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-2-3",
          serviceId: "analytics",
          name: "Onboarding Funnel",
          description: "First-session activation",
          status: "draft",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-2-4",
          serviceId: "analytics",
          name: "Trial Conversion",
          description: "Trial to paid path",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-2-5",
          serviceId: "analytics",
          name: "Reactivation Funnel",
          description: "Return after dormancy",
          status: "draft",
          isVisible: false,
          isFeatured: false,
        },
      ],
    },
    {
      id: "a-3",
      serviceId: "analytics",
      name: "Acquisition",
      description: "Traffic sources and campaigns",
      status: "published",
      isVisible: true,
      isFeatured: false,
      children: [
        {
          id: "a-3-1",
          serviceId: "analytics",
          name: "Paid Search",
          description: "SEM performance by keyword",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-3-2",
          serviceId: "analytics",
          name: "Organic Social",
          description: "Social referrals and engagement",
          status: "review",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-3-3",
          serviceId: "analytics",
          name: "Referrals",
          description: "Partner and user referrals",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-3-4",
          serviceId: "analytics",
          name: "Partnerships",
          description: "Co-marketing attribution",
          status: "draft",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-3-5",
          serviceId: "analytics",
          name: "Content Marketing",
          description: "Blog and resource performance",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-3-6",
          serviceId: "analytics",
          name: "Email Campaigns",
          description: "Lifecycle email metrics",
          status: "review",
          isVisible: true,
          isFeatured: false,
        },
      ],
    },
    {
      id: "a-4",
      serviceId: "analytics",
      name: "Retention",
      description: "Engagement and churn signals",
      status: "review",
      isVisible: true,
      isFeatured: false,
      children: [
        {
          id: "a-4-1",
          serviceId: "analytics",
          name: "Cohort Analysis",
          description: "Retention by signup cohort",
          status: "published",
          isVisible: true,
          isFeatured: true,
        },
        {
          id: "a-4-2",
          serviceId: "analytics",
          name: "Churn Predictors",
          description: "Risk scoring and alerts",
          status: "draft",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-4-3",
          serviceId: "analytics",
          name: "Engagement Score",
          description: "Composite activity index",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-4-4",
          serviceId: "analytics",
          name: "Session Depth",
          description: "Pages and time per session",
          status: "review",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-4-5",
          serviceId: "analytics",
          name: "Feature Adoption",
          description: "Usage of key capabilities",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-4-6",
          serviceId: "analytics",
          name: "NPS Tracking",
          description: "Survey results over time",
          status: "draft",
          isVisible: false,
          isFeatured: false,
        },
        {
          id: "a-4-7",
          serviceId: "analytics",
          name: "Win-back Flows",
          description: "Re-engagement campaigns",
          status: "review",
          isVisible: true,
          isFeatured: false,
        },
      ],
    },
    {
      id: "a-5",
      serviceId: "analytics",
      name: "Revenue",
      description: "Monetization and forecasting",
      status: "published",
      isVisible: true,
      isFeatured: true,
      children: [
        {
          id: "a-5-1",
          serviceId: "analytics",
          name: "MRR Breakdown",
          description: "Monthly recurring components",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-5-2",
          serviceId: "analytics",
          name: "ARR Forecast",
          description: "Rolling annual projection",
          status: "review",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-5-3",
          serviceId: "analytics",
          name: "Expansion Revenue",
          description: "Upsell and cross-sell",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-5-4",
          serviceId: "analytics",
          name: "Contraction Analysis",
          description: "Downgrades and partial churn",
          status: "draft",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-5-5",
          serviceId: "analytics",
          name: "Pricing Experiments",
          description: "Elasticity and willingness to pay",
          status: "review",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-5-6",
          serviceId: "analytics",
          name: "Usage-based Billing",
          description: "Metered consumption revenue",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-5-7",
          serviceId: "analytics",
          name: "Discounts & Credits",
          description: "Promotional impact on margin",
          status: "draft",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-5-8",
          serviceId: "analytics",
          name: "Geo Revenue Split",
          description: "Revenue by region",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
      ],
    },
    {
      id: "a-6",
      serviceId: "analytics",
      name: "Experiments",
      description: "Testing and rollout governance",
      status: "draft",
      isVisible: true,
      isFeatured: false,
      children: [
        {
          id: "a-6-1",
          serviceId: "analytics",
          name: "A/B Test Framework",
          description: "Experiment lifecycle",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-6-2",
          serviceId: "analytics",
          name: "Feature Flags",
          description: "Controlled exposure",
          status: "review",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-6-3",
          serviceId: "analytics",
          name: "Holdout Groups",
          description: "Long-term control cells",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-6-4",
          serviceId: "analytics",
          name: "Multivariate Tests",
          description: "Factorial designs",
          status: "draft",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-6-5",
          serviceId: "analytics",
          name: "Guardrail Metrics",
          description: "Safety checks during ramps",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-6-6",
          serviceId: "analytics",
          name: "Sample Size Calculator",
          description: "Power and duration estimates",
          status: "review",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-6-7",
          serviceId: "analytics",
          name: "Ramp-up Schedule",
          description: "Gradual traffic allocation",
          status: "draft",
          isVisible: false,
          isFeatured: false,
        },
        {
          id: "a-6-8",
          serviceId: "analytics",
          name: "Novelty Effect Monitor",
          description: "Early lift vs steady state",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
        {
          id: "a-6-9",
          serviceId: "analytics",
          name: "Post-experiment Analysis",
          description: "Readouts and decisions",
          status: "review",
          isVisible: true,
          isFeatured: true,
        },
        {
          id: "a-6-10",
          serviceId: "analytics",
          name: "Experiment Catalog",
          description: "Historical tests registry",
          status: "published",
          isVisible: true,
          isFeatured: false,
        },
      ],
    },
  ],
  billing: [
    {
      id: "b-1",
      serviceId: "billing",
      name: "Invoices",
      description: "Invoice list and statuses",
      status: "draft",
      isVisible: false,
      isFeatured: false,
    },
    {
      id: "b-2",
      serviceId: "billing",
      name: "Transactions",
      description: "Recent transaction feed",
      status: "published",
      isVisible: true,
      isFeatured: false,
    },
  ],
  support: [
    {
      id: "s-1",
      serviceId: "support",
      name: "Tickets",
      description: "Incoming support requests",
      status: "published",
      isVisible: true,
      isFeatured: false,
    },
    {
      id: "s-2",
      serviceId: "support",
      name: "SLA Monitor",
      description: "SLA compliance metrics",
      status: "review",
      isVisible: true,
      isFeatured: true,
    },
  ],
};

export const slidesMock: Record<string, Slide[]> = Object.fromEntries(
  Object.entries(slidesSeed).map(([serviceId, slides]) => [serviceId, normalizeSlidesOrder(slides)]),
) as Record<string, Slide[]>;

export const fencesMock: Record<string, FenceMonth[]> = {
  analytics: buildFenceMonths("analytics", 4),
  billing: buildFenceMonths("billing", 4),
  support: buildFenceMonths("support", 4),
};
